const tweaks=[];
function reg(id,name,category,path,key,value,description,recommended=false){tweaks.push({id,name,category,path,key,value,description,recommended,type:'DWord',restart:true});}
const cv='HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion';
reg('game-mode','Enable Windows Game Mode','Gaming',cv+'\\GameBar','AutoGameModeEnabled',1,'Lets Windows prioritize game workloads.',true);
reg('capture','Disable background game recording','Gaming',cv+'\\GameDVR','AppCaptureEnabled',0,'Stops Windows gameplay capture. Recording features will be unavailable.',true);
reg('dvr','Disable Game DVR','Gaming','HKCU:\\System\\GameConfigStore','GameDVR_Enabled',0,'Disables Game DVR recording.',true);
reg('mouse','Disable mouse acceleration','Gaming','HKCU:\\Control Panel\\Mouse','MouseSpeed','0','Uses consistent pointer movement. Games with raw input may be unaffected.',true);
reg('mouse1','Remove pointer acceleration threshold 1','Gaming','HKCU:\\Control Panel\\Mouse','MouseThreshold1','0','Complements disabling pointer acceleration.',true);
reg('mouse2','Remove pointer acceleration threshold 2','Gaming','HKCU:\\Control Panel\\Mouse','MouseThreshold2','0','Complements disabling pointer acceleration.',true);
reg('transparency','Disable interface transparency','Windows',cv+'\\Themes\\Personalize','EnableTransparency',0,'Reduces desktop visual effects.',true);
reg('animations','Disable taskbar animations','Windows',cv+'\\Explorer\\Advanced','TaskbarAnimations',0,'Reduces taskbar animation work.',true);
reg('widgets','Hide taskbar widgets','Debloat',cv+'\\Explorer\\Advanced','TaskbarDa',0,'Hides the widgets entry; does not uninstall the component.');
reg('chat','Hide taskbar chat','Debloat',cv+'\\Explorer\\Advanced','TaskbarMn',0,'Hides the Windows 11 chat entry where supported.');
reg('taskview','Hide Task View button','Windows',cv+'\\Explorer\\Advanced','ShowTaskViewButton',0,'Simplifies the taskbar.');
reg('search','Hide taskbar search box','Windows',cv+'\\Search','SearchboxTaskbarMode',0,'Hides the search box; Windows search remains available.');
reg('startup','Disable startup app notifications','Windows',cv+'\\Explorer\\Advanced','StartupNotify',0,'Reduces startup app notifications where supported.');
reg('shake','Disable Aero Shake','Windows',cv+'\\Explorer\\Advanced','DisallowShaking',1,'Prevents shaking a window from minimizing others.');
reg('snap','Disable snap assist suggestions','Windows',cv+'\\Explorer\\Advanced','SnapAssist',0,'Stops snap suggestions where supported.');
reg('tracking','Disable app launch tracking','Privacy',cv+'\\Explorer\\Advanced','Start_TrackProgs',0,'Stops Start menu app launch tracking.');
reg('recent','Disable recent document tracking','Privacy',cv+'\\Explorer\\Advanced','Start_TrackDocs',0,'Removes recent document lists.');
reg('sync-notice','Hide Explorer provider notifications','Debloat',cv+'\\Explorer\\Advanced','ShowSyncProviderNotifications',0,'Hides promotional provider notifications in Explorer.',true);
reg('ads','Disable advertising ID','Privacy',cv+'\\AdvertisingInfo','Enabled',0,'Disables the current user advertising identifier.',true);
reg('tailored','Disable tailored diagnostic experiences','Privacy',cv+'\\Privacy','TailoredExperiencesWithDiagnosticDataEnabled',0,'Stops personalized suggestions from diagnostic data.',true);
reg('input','Disable input personalization','Privacy','HKCU:\\Software\\Microsoft\\Personalization\\Settings','AcceptedPrivacyPolicy',0,'Disables optional input personalization; may affect suggestions.');
reg('ink','Restrict ink collection','Privacy','HKCU:\\Software\\Microsoft\\InputPersonalization','RestrictImplicitInkCollection',1,'Limits handwriting personalization.');
reg('text','Restrict text collection','Privacy','HKCU:\\Software\\Microsoft\\InputPersonalization','RestrictImplicitTextCollection',1,'Limits text personalization.');
reg('contacts','Disable harvested contact personalization','Privacy','HKCU:\\Software\\Microsoft\\InputPersonalization\\TrainedDataStore','HarvestContacts',0,'Stops contacts being used for input personalization.');
reg('feedback','Reduce feedback prompts','Privacy',cv+'\\Siuf\\Rules','NumberOfSIUFInPeriod',0,'Reduces Windows feedback prompts.');
reg('clipboard','Disable clipboard history','Privacy','HKCU:\\Software\\Microsoft\\Clipboard','EnableClipboardHistory',0,'Turns off clipboard history; previously stored entries are not erased.');
reg('clipboard-sync','Disable cross-device clipboard','Privacy','HKCU:\\Software\\Microsoft\\Clipboard','EnableCloudClipboard',0,'Turns off clipboard cloud sync.');
const content=[['ContentDeliveryAllowed','Disable content delivery'],['OemPreInstalledAppsEnabled','Disable OEM app suggestions'],['PreInstalledAppsEnabled','Disable preinstalled app suggestions'],['PreInstalledAppsEverEnabled','Disable future preinstalled app suggestions'],['SilentInstalledAppsEnabled','Disable silent suggested app installs'],['SoftLandingEnabled','Disable Windows tips'],['SystemPaneSuggestionsEnabled','Disable Settings suggestions'],['SubscribedContent-338388Enabled','Disable Start suggestions'],['SubscribedContent-338389Enabled','Disable tips and tricks'],['SubscribedContent-353694Enabled','Disable Settings promotional content'],['SubscribedContent-353696Enabled','Disable additional Settings suggestions'],['SubscribedContent-338393Enabled','Disable suggested notifications'],['SubscribedContent-310093Enabled','Disable welcome content'],['SubscribedContent-338387Enabled','Disable lock screen tips'],['RotatingLockScreenEnabled','Disable rotating lock screen images'],['RotatingLockScreenOverlayEnabled','Disable lock screen promotional overlays']];
content.forEach(([key,name],i)=>reg('content-'+i,name,'Debloat',cv+'\\ContentDeliveryManager',key,0,'Reduces Windows suggested content where supported. This is not an FPS guarantee.',i<7));
reg('welcome','Disable Windows welcome experience','Debloat',cv+'\\UserProfileEngagement','ScoobeSystemSettingEnabled',0,'Stops additional setup suggestions after sign-in.',true);
reg('toast','Disable toast notifications','Windows',cv+'\\PushNotifications','ToastEnabled',0,'Disables app toast notifications; you may miss useful alerts.');
reg('notification-sound','Disable notification sounds','Windows',cv+'\\Notifications\\Settings','NOC_GLOBAL_SETTING_ALLOW_NOTIFICATION_SOUND',0,'Keeps notifications quiet.');
reg('lock-notifications','Disable lock screen notifications','Privacy',cv+'\\Notifications\\Settings','NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK',0,'Hides toast notifications above the lock screen.');
reg('lock-reminders','Disable lock screen reminders','Privacy',cv+'\\Notifications\\Settings','NOC_GLOBAL_SETTING_ALLOW_CRITICAL_TOASTS_ABOVE_LOCK',0,'Hides reminder notifications on the lock screen.');
reg('edge-startup','Disable Edge startup boost','Debloat','HKCU:\\Software\\Policies\\Microsoft\\Edge','StartupBoostEnabled',0,'Prevents Edge startup preloading where the policy is supported.',true);
reg('edge-background','Disable Edge background mode','Debloat','HKCU:\\Software\\Policies\\Microsoft\\Edge','BackgroundModeEnabled',0,'Stops Edge background apps after the browser closes.',true);
reg('edge-first','Disable Edge first run experience','Debloat','HKCU:\\Software\\Policies\\Microsoft\\Edge','HideFirstRunExperience',1,'Hides Edge first run prompts.');
reg('edge-personalization','Disable Edge personalized ads','Privacy','HKCU:\\Software\\Policies\\Microsoft\\Edge','PersonalizationReportingEnabled',0,'Disables Edge personalization reporting.');
reg('edge-metrics','Disable optional Edge metrics','Privacy','HKCU:\\Software\\Policies\\Microsoft\\Edge','MetricsReportingEnabled',0,'Disables optional browser metrics where supported.');
reg('edge-shopping','Disable Edge shopping assistant','Debloat','HKCU:\\Software\\Policies\\Microsoft\\Edge','EdgeShoppingAssistantEnabled',0,'Disables shopping suggestions.');
reg('edge-recommendations','Disable Edge feature recommendations','Debloat','HKCU:\\Software\\Policies\\Microsoft\\Edge','ShowRecommendationsEnabled',0,'Hides browser feature recommendations.');
reg('office-telemetry','Disable Office client telemetry','Privacy','HKCU:\\Software\\Policies\\Microsoft\\Office\\16.0\\Common','sendcustomerdata',0,'Opts out of Office customer experience data where supported.');
reg('office-feedback','Disable Office feedback prompts','Privacy','HKCU:\\Software\\Policies\\Microsoft\\Office\\16.0\\Common\\Feedback','enabled',0,'Disables Office feedback prompts where supported.');
reg('accessibility','Disable Sticky Keys hotkey','Gaming','HKCU:\\Control Panel\\Accessibility\\StickyKeys','Flags','506','Prevents Shift presses from triggering Sticky Keys. Changes accessibility behavior.');
reg('filter-keys','Disable Filter Keys hotkey','Gaming','HKCU:\\Control Panel\\Accessibility\\Keyboard Response','Flags','122','Prevents holding Shift from enabling Filter Keys. Changes accessibility behavior.');
reg('toggle-keys','Disable Toggle Keys hotkey','Gaming','HKCU:\\Control Panel\\Accessibility\\ToggleKeys','Flags','58','Disables the Toggle Keys hotkey. Changes accessibility behavior.');
for(const t of tweaks) if(typeof t.value==='string') t.type='String';
function recommendedIds(scan){return tweaks.filter(t=>t.recommended && (!scan || scan.platform==='win32')).map(t=>t.id);}
module.exports={tweaks,recommendedIds};
