'use strict';
const $=id=>document.getElementById(id);
let catalog=[],selected=new Set(),scanData,active=[],pendingIds=[],entries={},history=[],isWindows=false,scanReady=false,busy=false,pending='apply',samples=[],benchmarkEntries=[];
const titles={dashboard:'Command center',tweaks:'Optimizations',hardware:'Your hardware',network:'Connection lab',benchmark:'Benchmark journal',recovery:'Recovery vault'};
function banner(text){$('banner').textContent=text;}
function page(id){document.querySelectorAll('.page').forEach(el=>el.classList.toggle('hidden',el.id!==id));document.querySelectorAll('.nav').forEach(el=>{el.classList.toggle('active',el.dataset.page===id);el.setAttribute('aria-current',el.dataset.page===id?'page':'false');});$('page-title').textContent=titles[id];}
function element(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function gb(n){return (n/2**30).toFixed(1)+' GB';}
function syncButtons(){$('apply').disabled=busy||!scanReady||!selected.size;$('restore').disabled=busy||!isWindows||!pendingIds.length;$('rescan').disabled=busy;$('performance').disabled=busy||!scanReady;$('recommended').disabled=busy||!scanReady;$('select-recommended').disabled=busy||!scanReady;$('select-all').disabled=busy||!scanReady;}
function count(){$('selection-count').textContent=`${selected.size} selected · ${catalog.filter(t=>t.available).length} compatible`;syncButtons();}
function draw(){const term=$('search').value.trim().toLowerCase(),cat=$('category').value;const list=$('tweak-list');list.replaceChildren();const filtered=catalog.filter(t=>(cat==='All categories'||cat===t.category)&&(t.name+' '+t.description).toLowerCase().includes(term));if(!filtered.length)list.append(element('p','No tweaks match your search.','empty-state'));for(const t of filtered){const label=element('label',undefined,'tweak'+(!t.available?' unavailable':''));const check=document.createElement('input');check.type='checkbox';check.checked=selected.has(t.id);check.disabled=busy||!t.available;check.setAttribute('aria-label',t.name);check.onchange=()=>{if(check.checked){if(t.exclusive)catalog.filter(other=>other.exclusive===t.exclusive).forEach(other=>selected.delete(other.id));selected.add(t.id);}else selected.delete(t.id);draw();};const content=document.createElement('div');content.append(element('h3',t.name),element('p',t.description),element('span',t.category.toUpperCase(),'badge'));if(t.recommended)content.append(element('span','RECOMMENDED','badge green'));if(entries[t.id])content.append(element('span',entries[t.id].status.toUpperCase(),'badge'));content.append(element('small',t.available?t.caution:t.reason,'tradeoff'));label.append(check,content);list.append(label);}count();}
async function recommendations(mode='recommended'){try{const result=await window.agent.profile(mode);selected=new Set(result.ids);$('search').value='';$('category').value='All categories';page('tweaks');draw();banner(`${mode==='performance'?'Performance':'Recommended'} profile: ${selected.size} compatible settings selected for ${scanData.cpu}. Review the feature tradeoffs before applying.`);}catch(e){banner(e.message);}}
function showHistory(){if(!history.length){$('operation-log').textContent='No operations recorded.';return;}$('operation-log').textContent=[...history].reverse().map(item=>`${new Date(item.time).toLocaleString()} · ${item.operation.toUpperCase()}\n`+item.results.map(r=>`  ${r.status.toUpperCase()} · ${catalog.find(t=>t.id===r.id)?.name||r.id}${r.error?' — '+r.error:''}`).join('\n')).join('\n\n');}
async function refresh(){const data=await window.agent.catalog();catalog=data.tweaks;entries=data.entries||{};history=data.history||[];active=data.active||[];pendingIds=data.pending||Object.keys(entries);isWindows=data.windows;$('total').textContent=catalog.length;$('nav-total').textContent=catalog.length;$('active').textContent=active.length;$('backups').textContent=pendingIds.length;$('supported-total').textContent=catalog.filter(t=>t.available).length+' compatible with your scan';$('version').textContent='AGENT TWEAKS / '+data.version;selected=new Set([...selected].filter(id=>catalog.some(t=>t.id===id&&t.available)));draw();showHistory();}
function hardware(){const data=[['▦','PROCESSOR',scanData.cpu,`${scanData.cores} physical cores · ${scanData.logicalCores} threads`],['◈','GRAPHICS',scanData.gpu.map(g=>g.name).join(', ')||'Not detected',scanData.gpu.length?'Driver '+scanData.gpu.map(g=>g.driver).join(', '):'GPU scan requires Windows'],['▤','MEMORY & STORAGE',gb(scanData.ram)+' RAM',scanData.disks.map(d=>`${d.name} ${gb(d.total-d.free)} / ${gb(d.total)} used`).join(' · ')||'Storage scan requires Windows']];$('hardware-cards').replaceChildren();for(const [icon,title,value,detail] of data){const card=element('article',undefined,'hardware-card');card.append(element('div',icon,'symbol'),element('span',title),element('strong',value),element('small',detail));$('hardware-cards').append(card);}$('hardware-details').textContent=JSON.stringify(scanData,null,2);const rows=[['Processor',scanData.cpu],['Graphics',scanData.gpu.map(g=>g.name).join(', ')||'Unavailable'],['Physical memory',gb(scanData.ram)],['Windows',scanData.os+(scanData.build?' · build '+scanData.build:'')],['Chassis',scanData.desktop?'Desktop':'Portable / other'],['Active power plan',scanData.powerPlans.find(p=>p.active)?.name||'Unavailable'],['Network adapters',scanData.network.map(n=>`${n.name} · ${n.linkSpeed}`).join(', ')||'Unavailable']];$('hardware-table').replaceChildren();for(const [name,value] of rows){const row=element('div',undefined,'hardware-row');row.append(element('span',name),element('strong',value));$('hardware-table').append(row);}}
async function rescan(){if(busy)return;busy=true;scanReady=false;syncButtons();$('scan-badge').textContent='Scanning…';try{scanData=await window.agent.scan();isWindows=scanData.platform==='win32';scanReady=!!scanData.scanComplete&&isWindows;hardware();$('scan-badge').textContent=scanReady?'● PC SCANNED':'PREVIEW MODE';$('scan-time').textContent=scanData.scannedAt?'Scanned '+new Date(scanData.scannedAt).toLocaleTimeString():'Local hardware scan';const p=await window.agent.profile('performance');$('profile-tips').replaceChildren(...p.tips.map(t=>element('li',t)));banner(scanReady?(scanData.warnings.length?scanData.warnings.join(' '):'Scan complete. Compatible options are ready; nothing has been changed.'):'Preview on '+scanData.os+'. Applying Windows settings requires Windows.');}catch(e){scanReady=false;$('scan-badge').textContent='SCAN FAILED';banner('Scan failed. Applying settings is disabled. '+e.message);}finally{try{await refresh();}catch(e){banner('Recovery data could not be loaded. '+e.message);}busy=false;draw();}}
function review(kind){if(busy)return;pending=kind;if(kind==='apply'&&(!scanReady||!selected.size))return;if(kind==='restore'&&!pendingIds.length)return;const chosen=kind==='apply'?[...selected]:pendingIds;$('review-title').textContent=kind==='apply'?'Your profile. Your choice.':'Restore your original settings';$('review-summary').textContent=kind==='apply'?`${chosen.length} supported settings selected. Power changes affect the machine; registry changes affect your Windows account.`:`${chosen.length} recovery records. Each original value is verified before its backup is cleared.`;$('review-list').replaceChildren();for(const t of catalog.filter(t=>chosen.includes(t.id))){const item=element('div',undefined,'review-item');item.append(element('strong',t.name),element('small',kind==='apply'?t.description:'Original value and type will be restored.'));$('review-list').append(item);}$('confirm').textContent=kind==='apply'?'Apply reviewed settings':'Restore original settings';$('review').showModal();}
async function confirm(){const ids=[...selected];const operation=pending;$('review').close();busy=true;draw();banner('Saving original settings and processing changes. Do not close the app…');try{const results=await(operation==='apply'?window.agent.apply(ids):window.agent.restore());const changed=results.filter(r=>r.status==='applied'||r.status==='restored').length,already=results.filter(r=>r.status==='already').length,failed=results.filter(r=>r.status==='failed').length,skipped=results.filter(r=>r.status==='skipped').length;banner(`${changed} verified changes · ${already} already configured · ${failed} failed · ${skipped} skipped. See Recovery for details. Restart your game or sign out for relevant settings.`);await refresh();}catch(e){banner('Operation stopped: '+e.message+' Recovery keeps any saved original values.');try{await refresh();}catch{}}finally{busy=false;draw();}}
function chart(){const canvas=$('cpu-chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#263149';ctx.lineWidth=1;for(let y=10;y<h;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}if(samples.length<2)return;ctx.beginPath();samples.forEach((v,i)=>{const x=i/(Math.max(samples.length-1,1))*w,y=h-10-v*(h-20)/100;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.strokeStyle='#699fff';ctx.lineWidth=3;ctx.stroke();ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();const gradient=ctx.createLinearGradient(0,0,0,h);gradient.addColorStop(0,'#448aff45');gradient.addColorStop(1,'#448aff00');ctx.fillStyle=gradient;ctx.fill();}
async function metrics(){try{const m=await window.agent.metrics();$('memory').textContent=Math.round(m.ramUsed/m.ram*100)+'%';$('memory-detail').textContent=gb(m.ramUsed)+' / '+gb(m.ram);$('memory-bar').style.width=Math.round(m.ramUsed/m.ram*100)+'%';if(Number.isFinite(m.cpu)){$('cpu-load').textContent=m.cpu+'%';samples.push(m.cpu);samples=samples.slice(-30);chart();}}catch{}}
async function probe(){$('probe').disabled=true;$('network-result').textContent='Measuring 5 connections…';try{const r=await window.agent.network();$('network-result').textContent=r.error||`${r.ms} ms median`;$('network-detail').textContent=r.error?'Check your connection and try again.':`Range ${r.min}–${r.max} ms · spread ${r.jitter} ms · ${r.failed}/${r.sent} failed connections. TCP setup timing is not in-game ping.`;$('ping').textContent=r.error?'Unavailable':r.ms+' ms';}catch(e){$('network-result').textContent=e.message;}finally{$('probe').disabled=false;}}
function showBenchmarks(){$('benchmark-history').textContent=benchmarkEntries.length?[...benchmarkEntries].reverse().map(r=>`${r.game} · ${new Date(r.time).toLocaleString()}\nAverage: ${r.beforeFps} → ${r.afterFps} FPS (${r.averageChange>=0?'+':''}${r.averageChange}%)\n1% low: ${r.beforeLow} → ${r.afterLow} FPS (${r.lowChange>=0?'+':''}${r.lowChange}%)`).join('\n\n'):'No benchmark entries yet.';}
function benchmark(){try{const result=window.AgentBenchmark.compare({game:$('benchmark-game').value,beforeFps:Number($('before-fps').value),beforeLow:Number($('before-low').value),afterFps:Number($('after-fps').value),afterLow:Number($('after-low').value)});benchmarkEntries.push(result);benchmarkEntries=benchmarkEntries.slice(-50);localStorage.setItem('agent-benchmarks-v2',JSON.stringify(benchmarkEntries));$('benchmark-result').textContent=`Measured average FPS change: ${result.averageChange>=0?'+':''}${result.averageChange}% · 1% low change: ${result.lowChange>=0?'+':''}${result.lowChange}%.`;showBenchmarks();}catch(e){$('benchmark-result').textContent=e.message;}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll('.settings').forEach(b=>b.onclick=async()=>{try{await window.agent.settings(b.dataset.setting);}catch(e){banner(e.message);}});$('rescan').onclick=rescan;$('performance').onclick=()=>recommendations('performance');$('recommended').onclick=()=>recommendations();$('select-recommended').onclick=()=>recommendations();$('open-benchmark').onclick=()=>page('benchmark');$('select-all').onclick=()=>{selected.clear();const groups=new Set();for(const t of catalog.filter(t=>t.available)){if(t.exclusive&&groups.has(t.exclusive))continue;selected.add(t.id);if(t.exclusive)groups.add(t.exclusive);}draw();};$('clear').onclick=()=>{selected.clear();draw();};$('search').oninput=draw;$('category').onchange=draw;$('apply').onclick=()=>review('apply');$('restore').onclick=()=>review('restore');$('cancel').onclick=()=>$('review').close();$('confirm').onclick=confirm;$('probe').onclick=probe;$('compare-benchmark').onclick=benchmark;$('export-report').onclick=async()=>{try{if(await window.agent.report())banner('Diagnostics saved locally. Review the file before sharing it.');}catch(e){banner(e.message);}};$('backup-folder').onclick=async()=>{try{await window.agent.backupFolder();}catch(e){banner(e.message);}};
try{const saved=JSON.parse(localStorage.getItem('agent-benchmarks-v2')||'[]');if(Array.isArray(saved))benchmarkEntries=saved.slice(-50);}catch{}showBenchmarks();syncButtons();rescan();metrics();setInterval(metrics,2500);
