const $=id=>document.getElementById(id);let catalog=[],selected=new Set(),scanData,active=[],isWindows=false,pending='apply';
function banner(s){$('banner').textContent=s;}
function page(id){document.querySelectorAll('.page').forEach(el=>el.classList.toggle('hidden',el.id!==id));document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.page===id));$('page-title').textContent={dashboard:'Overview',tweaks:'Optimizations',hardware:'My hardware',network:'Network & latency',recovery:'Recovery'}[id];}
function count(){$('selection-count').textContent=`${selected.size} selected / ${catalog.length} available`;}
function draw(){const term=$('search').value.toLowerCase(),cat=$('category').value;$('tweak-list').replaceChildren();catalog.filter(t=>(cat==='All categories'||cat===t.category)&&(t.name+' '+t.description).toLowerCase().includes(term)).forEach(t=>{const label=document.createElement('label');label.className='tweak';const check=document.createElement('input');check.type='checkbox';check.checked=selected.has(t.id);check.setAttribute('aria-label',t.name);check.onchange=()=>{check.checked?selected.add(t.id):selected.delete(t.id);count();};const content=document.createElement('div');const h=document.createElement('h3');h.textContent=t.name;const p=document.createElement('p');p.textContent=t.description;const badge=document.createElement('span');badge.className='badge';badge.textContent=t.category.toUpperCase();content.append(h,p,badge);if(t.recommended){const b=document.createElement('span');b.className='badge green';b.textContent='RECOMMENDED';content.append(b);}if(active.includes(t.id)){const b=document.createElement('span');b.className='badge';b.textContent='BACKED UP';content.append(b);}label.append(check,content);$('tweak-list').append(label);});count();}
function recommendations(performance=false){selected=new Set(catalog.filter(t=>t.recommended && isWindows && (!performance||scanData?.desktop||t.category!=='Gaming')).map(t=>t.id));page('tweaks');draw();if(!isWindows)banner('Preview mode: recommendations and Windows changes require a Windows hardware scan.');else banner(`${performance?'Performance':'Recommended'} profile: ${scanData.cpu}, ${Math.round(scanData.ram/2**30)} GB RAM${scanData.desktop?' · desktop':' · portable/unknown chassis'}. Review the settings below. No power or driver changes are made automatically.`);}
function gb(n){return (n/2**30).toFixed(1)+' GB';}
async function rescan(){try{$('rescan').disabled=true;scanData=await window.agent.scan();isWindows=scanData.platform==='win32';if(!isWindows)banner('Interface preview on '+scanData.os+'. Windows scanning and registry changes are available in the Windows installer.');$('memory').textContent=Math.round(scanData.ramUsed/scanData.ram*100)+'%';$('memory-bar').style.width=Math.round(scanData.ramUsed/scanData.ram*100)+'%';$('hardware-cards').replaceChildren();const data=[['▦','PROCESSOR',scanData.cpu,`${scanData.cores} cores detected`],['◈','GRAPHICS',scanData.gpu.map(g=>g.name).join(', ')||'Windows scanner required','Drivers detected locally on Windows'],['▤','MEMORY & STORAGE',gb(scanData.ram)+' RAM',scanData.disks.map(d=>`${d.name} ${gb(d.total-d.free)} / ${gb(d.total)} used`).join(' · ')||'Storage scan requires Windows']];for(const [icon,title,value,detail] of data){const a=document.createElement('article');a.className='hardware-card';for(const [tag,txt,cls] of [['div',icon,'symbol'],['span',title,''],['strong',value,''],['small',detail,'']]){const e=document.createElement(tag);e.textContent=txt;e.className=cls;a.append(e);}$('hardware-cards').append(a);}$('hardware-details').textContent=JSON.stringify(scanData,null,2);$('apply').disabled=!isWindows;$('restore').disabled=!isWindows;}catch(e){banner('Hardware scan failed: '+e.message);}finally{$('rescan').disabled=false;}}
async function refresh(){const data=await window.agent.catalog();catalog=data.tweaks;active=data.active;$('total').textContent=catalog.length;$('active').textContent=active.length;draw();}
function review(kind){pending=kind;if(kind==='apply'&&!selected.size){banner('Select at least one tweak.');return;}$('review-title').textContent=kind==='apply'?'Review your changes':'Restore original values';$('review-summary').textContent=kind==='apply'?`${selected.size} registry settings will be changed for your current Windows user.`:`Restore ${active.length} backed-up settings to their original values.`;$('review-list').replaceChildren();for(const t of catalog.filter(t=>(kind==='apply'?selected:new Set(active)).has(t.id))){const p=document.createElement('div');p.textContent=t.name;$('review-list').append(p);}$('confirm').textContent=kind==='apply'?'Apply changes':'Restore settings';$('review').showModal();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll('.settings').forEach(b=>b.onclick=()=>window.agent.settings(b.dataset.setting));$('rescan').onclick=rescan;$('performance').onclick=()=>recommendations(true);$('recommended').onclick=()=>recommendations();$('select-recommended').onclick=()=>recommendations();$('select-all').onclick=()=>{selected=new Set(catalog.map(t=>t.id));draw();};$('clear').onclick=()=>{selected.clear();draw();};$('search').oninput=draw;$('category').onchange=draw;$('apply').onclick=()=>review('apply');$('restore').onclick=()=>review('restore');$('cancel').onclick=()=>$('review').close();$('confirm').onclick=async()=>{$('review').close();$('apply').disabled=true;$('restore').disabled=true;banner('Saving backups and processing settings…');try{const results=await(pending==='apply'?window.agent.apply([...selected]):window.agent.restore());const failed=results.filter(r=>!r.ok);$('operation-log').textContent=results.map(r=>`${r.ok?'OK':'FAILED'} · ${catalog.find(t=>t.id===r.id)?.name}: ${r.error||'completed'}`).join('\n');banner(`${results.length-failed.length} settings completed, ${failed.length} failed. See Recovery for results. Sign out or restart to let Windows reload changed settings.`);await refresh();}catch(e){banner(e.message);}finally{$('apply').disabled=!isWindows;$('restore').disabled=!isWindows;}};
async function probe(){$('probe').disabled=true;try{const r=await window.agent.network();$('network-result').textContent=r.error||`${r.ms} ms · ${r.target}`;$('ping').textContent=r.error?'Unavailable':r.ms+' ms';}finally{$('probe').disabled=false;}}
$('probe').onclick=probe;Promise.all([refresh(),rescan()]).catch(e=>banner(e.message));
